#!/bin/bash

for g in faculty-base staff-base students-base dcc-base retirees-base hsl-base
do
    /usr/bin/petl --config /etc/petal/petl.ini \
                  --group ${g} \
                  --ldap_passwd ${LDAP_PASSWD} \
                  --grouper_passwd ${GROUPER_PASSWD} \
                  --slack ${SLACK_WEBHOOK} \
                  --sync
done
